spring.datasource.url=jdbc:mysql://localhost:3306/crimson_code
spring.datasource.username=crimson_code_dev
spring.datasource.password=crimson_code_dev

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web: DEBUG

tokenSecert=34743777217A25432A46294A404E635266556A586E3272357538782F413F4428

# 10 day
emailVerificationTokenExpirationDate=864000000