package com.crimson_code_blog_rest_apis.utils;

public enum OperationName {
	VERIFIY_USER_EMAIL,
	EMAIL_VERIFICATION_TOKEN_REQUEST,
	LOGOUT,
	DELETE_USER,
	PASSWORD_RESET_REQUEST,
	PASSWORD_RESET_CONFIRMATION,
	CHANGE_PASSWORD,
	DELETE_CATEGORY
}
